name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish python poetry package
      uses: JRubics/poetry-publish@v1.13
      with:
        python_version: '3.10'
        pypi_token: ${{ secrets.PYPI_API_TOKEN }}
